stage:
  last_harvest: calher130-stage/last-harvest.yml
  stop_file: calher130-stage/stop-tind-harvester.txt
  oai:
    base_url: https://berkeley-test.tind.io/oai2d
    set: calher130
  merritt:
    collection_ark: ark:/13030/m5vd6wc7
    database: database.yml
    ingest_url: http://merritt-stage.cdlib.org:33121/poster/submit/
    ingest_profile: ucb_lib_content
  log:
    file: calher130-stage/mrt-tind-harvester.log
    level: info
